apiVersion: phenix.sandia.gov/v2
kind: Scenario
metadata:
  name: hids
  annotations:
    topology: hids
spec:
  apps:
  - name: vrouter
    fromScenario: base
  - name: wireguard
    fromScenario: base
  - name: protonuke
    fromScenario: base
